name: "Continuous Deployment (CD)"

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'temp-ramy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Extract short SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t hiringultramy-app:${{ env.TAG }} .

      - name: Save Docker image to archive
        run: docker save hiringultramy-app:${{ env.TAG }} > hiringultramy-app-${{ env.TAG }}.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "hiringultramy-app-${{ env.TAG }}.tar"
          target: "~/deploys/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TAG=${{ env.TAG }}
            echo "Deploying version $TAG"
            docker load < ~/deploys/hiringultramy-app-${TAG}.tar
            docker stop hiringultramy || true
            docker rm hiringultramy || true
            docker run -d \
              --name hiringultramy \
              --restart unless-stopped \
              -p 8080:8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e JWT=${{ secrets.JWT }} \
              hiringultramy-app:${TAG}
            echo "$TAG" > ~/deploys/LATEST_DEPLOYED_TAG.txt
